// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: climb.sql

package database

import (
	"context"
	"database/sql"
)

const createArea = `-- name: CreateArea :one
INSERT INTO area(name, country, sub_areas, created_by)
VALUES ($1, $2, $3, $4)
RETURNING area_id, name, country, sub_areas, created_by, created_at, updated_at
`

type CreateAreaParams struct {
	Name      string
	Country   string
	SubAreas  string
	CreatedBy int32
}

func (q *Queries) CreateArea(ctx context.Context, arg CreateAreaParams) (Area, error) {
	row := q.db.QueryRowContext(ctx, createArea,
		arg.Name,
		arg.Country,
		arg.SubAreas,
		arg.CreatedBy,
	)
	var i Area
	err := row.Scan(
		&i.AreaID,
		&i.Name,
		&i.Country,
		&i.SubAreas,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClimb = `-- name: CreateClimb :one
INSERT INTO climb(area_id, name, type, created_by, sub_areas)
VALUES ($1, $2, $3, $4, $5)
RETURNING climb_id, area_id, name, type, created_by, created_at, updated_at, sub_areas
`

type CreateClimbParams struct {
	AreaID    int32
	Name      string
	Type      string
	CreatedBy int32
	SubAreas  sql.NullString
}

func (q *Queries) CreateClimb(ctx context.Context, arg CreateClimbParams) (Climb, error) {
	row := q.db.QueryRowContext(ctx, createClimb,
		arg.AreaID,
		arg.Name,
		arg.Type,
		arg.CreatedBy,
		arg.SubAreas,
	)
	var i Climb
	err := row.Scan(
		&i.ClimbID,
		&i.AreaID,
		&i.Name,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubAreas,
	)
	return i, err
}

const createClimbDraft = `-- name: CreateClimbDraft :one
INSERT INTO climb_draft(created_by, name, country, area_id, area, sub_areas, type)
VALUES ($1, $2, $3, $4, $5, $6, $7) 
ON CONFLICT ON CONSTRAINT climb_draft_pkey
DO UPDATE SET 
    created_by = $1, 
    name = $2, 
    country = $3, 
    area_id = $4, 
    area = $5, 
    sub_areas = $6, 
    type = $7,
    updated_at = now() 
RETURNING created_by, name, country, area_id, area, sub_areas, type, created_at, updated_at
`

type CreateClimbDraftParams struct {
	CreatedBy int32
	Name      string
	Country   string
	AreaID    sql.NullInt32
	Area      sql.NullString
	SubAreas  sql.NullString
	Type      string
}

func (q *Queries) CreateClimbDraft(ctx context.Context, arg CreateClimbDraftParams) (ClimbDraft, error) {
	row := q.db.QueryRowContext(ctx, createClimbDraft,
		arg.CreatedBy,
		arg.Name,
		arg.Country,
		arg.AreaID,
		arg.Area,
		arg.SubAreas,
		arg.Type,
	)
	var i ClimbDraft
	err := row.Scan(
		&i.CreatedBy,
		&i.Name,
		&i.Country,
		&i.AreaID,
		&i.Area,
		&i.SubAreas,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClimbDraft = `-- name: DeleteClimbDraft :one
DELETE FROM climb_draft
WHERE created_by = $1
RETURNING created_by, name, country, area_id, area, sub_areas, type, created_at, updated_at
`

func (q *Queries) DeleteClimbDraft(ctx context.Context, createdBy int32) (ClimbDraft, error) {
	row := q.db.QueryRowContext(ctx, deleteClimbDraft, createdBy)
	var i ClimbDraft
	err := row.Scan(
		&i.CreatedBy,
		&i.Name,
		&i.Country,
		&i.AreaID,
		&i.Area,
		&i.SubAreas,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArea = `-- name: GetArea :one
SELECT a.area_id, a.name, a.country, a.sub_areas
FROM area a
WHERE a.area_id = $1
`

type GetAreaRow struct {
	AreaID   int32
	Name     string
	Country  string
	SubAreas string
}

func (q *Queries) GetArea(ctx context.Context, areaID int32) (GetAreaRow, error) {
	row := q.db.QueryRowContext(ctx, getArea, areaID)
	var i GetAreaRow
	err := row.Scan(
		&i.AreaID,
		&i.Name,
		&i.Country,
		&i.SubAreas,
	)
	return i, err
}

const getClimb = `-- name: GetClimb :one
SELECT c.climb_id, c.name, c.area_id, c.sub_areas, c.type
FROM climb c 
WHERE c.climb_id = $1
`

type GetClimbRow struct {
	ClimbID  int32
	Name     string
	AreaID   int32
	SubAreas sql.NullString
	Type     string
}

func (q *Queries) GetClimb(ctx context.Context, climbID int32) (GetClimbRow, error) {
	row := q.db.QueryRowContext(ctx, getClimb, climbID)
	var i GetClimbRow
	err := row.Scan(
		&i.ClimbID,
		&i.Name,
		&i.AreaID,
		&i.SubAreas,
		&i.Type,
	)
	return i, err
}

const getClimbDraft = `-- name: GetClimbDraft :one
SELECT cd.created_by, cd.name, cd.country, cd.area_id, cd.area, cd.sub_areas, cd.type
FROM climb_draft cd
WHERE cd.created_by = $1
`

type GetClimbDraftRow struct {
	CreatedBy int32
	Name      string
	Country   string
	AreaID    sql.NullInt32
	Area      sql.NullString
	SubAreas  sql.NullString
	Type      string
}

func (q *Queries) GetClimbDraft(ctx context.Context, createdBy int32) (GetClimbDraftRow, error) {
	row := q.db.QueryRowContext(ctx, getClimbDraft, createdBy)
	var i GetClimbDraftRow
	err := row.Scan(
		&i.CreatedBy,
		&i.Name,
		&i.Country,
		&i.AreaID,
		&i.Area,
		&i.SubAreas,
		&i.Type,
	)
	return i, err
}

const getClimbsByArea = `-- name: GetClimbsByArea :many
SELECT c.climb_id, c.name, c.sub_areas, c.area_id, c.type
FROM climb c
WHERE c.area_id = $1
`

type GetClimbsByAreaRow struct {
	ClimbID  int32
	Name     string
	SubAreas sql.NullString
	AreaID   int32
	Type     string
}

func (q *Queries) GetClimbsByArea(ctx context.Context, areaID int32) ([]GetClimbsByAreaRow, error) {
	rows, err := q.db.QueryContext(ctx, getClimbsByArea, areaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClimbsByAreaRow
	for rows.Next() {
		var i GetClimbsByAreaRow
		if err := rows.Scan(
			&i.ClimbID,
			&i.Name,
			&i.SubAreas,
			&i.AreaID,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAreas = `-- name: SearchAreas :many
SELECT a.area_id, a.name, a.country, a.sub_areas
FROM area a
WHERE a.name % $1
ORDER BY similarity(a.name, $1) DESC, a.name
`

type SearchAreasRow struct {
	AreaID   int32
	Name     string
	Country  string
	SubAreas string
}

func (q *Queries) SearchAreas(ctx context.Context, name string) ([]SearchAreasRow, error) {
	rows, err := q.db.QueryContext(ctx, searchAreas, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAreasRow
	for rows.Next() {
		var i SearchAreasRow
		if err := rows.Scan(
			&i.AreaID,
			&i.Name,
			&i.Country,
			&i.SubAreas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClimbs = `-- name: SearchClimbs :many
SELECT c.climb_id, c.area_id, c.name, c.type
FROM climb c
WHERE c.type = $1
AND c.name % $2
ORDER BY similarity(c.name, $2) DESC, c.name
`

type SearchClimbsParams struct {
	Type string
	Name string
}

type SearchClimbsRow struct {
	ClimbID int32
	AreaID  int32
	Name    string
	Type    string
}

func (q *Queries) SearchClimbs(ctx context.Context, arg SearchClimbsParams) ([]SearchClimbsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchClimbs, arg.Type, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchClimbsRow
	for rows.Next() {
		var i SearchClimbsRow
		if err := rows.Scan(
			&i.ClimbID,
			&i.AreaID,
			&i.Name,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSubAreas = `-- name: SearchSubAreas :many
WITH sub_areas AS (
   SELECT a.area_id, a.name, unnest(string_to_array(a.sub_areas, ',')) as sub_area
   FROM area a ) 
SELECT sa.area_id, sa.name, sa.sub_area, similarity(sa.sub_area, $1) as sub_area_sml 
FROM sub_areas sa --WHERE sa.sub_area % $1
ORDER BY similarity(sa.sub_area, $1) DESC, sa.sub_area
`

type SearchSubAreasRow struct {
	AreaID     int32
	Name       string
	SubArea    interface{}
	SubAreaSml interface{}
}

func (q *Queries) SearchSubAreas(ctx context.Context, similarity interface{}) ([]SearchSubAreasRow, error) {
	rows, err := q.db.QueryContext(ctx, searchSubAreas, similarity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSubAreasRow
	for rows.Next() {
		var i SearchSubAreasRow
		if err := rows.Scan(
			&i.AreaID,
			&i.Name,
			&i.SubArea,
			&i.SubAreaSml,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubAreas = `-- name: UpdateSubAreas :one
UPDATE area
SET sub_areas = $1
WHERE area_id = $2
RETURNING area_id, name, country, sub_areas, created_by, created_at, updated_at
`

type UpdateSubAreasParams struct {
	SubAreas string
	AreaID   int32
}

func (q *Queries) UpdateSubAreas(ctx context.Context, arg UpdateSubAreasParams) (Area, error) {
	row := q.db.QueryRowContext(ctx, updateSubAreas, arg.SubAreas, arg.AreaID)
	var i Area
	err := row.Scan(
		&i.AreaID,
		&i.Name,
		&i.Country,
		&i.SubAreas,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
