// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Blog struct {
	BlogID      int32
	Body        []byte
	Title       string
	Excerpt     string
	IsPublished bool
	CreatedBy   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type BlogImg struct {
	ImgName   string
	Img       []byte
	BlogID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PlacementTest struct {
	PlacementTestID int32
	UserID          int32
	Score           int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ResetToken struct {
	Token      uuid.UUID
	Expiration time.Time
	Email      string
}

type TestQuestion struct {
	TestQuestionID int32
	QuestionText   string
	InputType      string
	Answers        string
	AnswerPoints   string
	Points         int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	UsersID   int32
	Username  string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Role      string
	SoulScore int32
}
