// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type ResetToken struct {
	Token      uuid.UUID
	Expiration time.Time
	Email      string
}

type User struct {
	UsersID   int32
	Username  string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
