-- +goose Up
CREATE TABLE country (
    name TEXT PRIMARY KEY
);

CREATE TABLE area (
    area_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    country TEXT NOT NULL REFERENCES country(name),
    sub_areas TEXT NOT NULL,
    created_by INT NOT NULL REFERENCES users(users_id),
    created_at TIMESTAMP NOT NULL DEFAULT current_date,
    updated_at TIMESTAMP NOT NULL DEFAULT current_date
);

CREATE TABLE climb (
    climb_id SERIAL PRIMARY KEY,
    area_id INT NOT NULL REFERENCES area(area_id),
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    created_by INT NOT NULL REFERENCES users(users_id),
    created_at TIMESTAMP NOT NULL DEFAULT current_date,
    updated_at TIMESTAMP NOT NULL DEFAULT current_date
);

CREATE TABLE climb_draft (
    created_by INT PRIMARY KEY REFERENCES users(users_id),
    name TEXT NOT NULL,
    country TEXT NOT NULL REFERENCES country(name),
    area_id INT REFERENCES area(area_id),
    area TEXT,
    sub_areas TEXT,
    type TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT current_date,
    updated_at TIMESTAMP NOT NULL DEFAULT current_date
);

create TABLE ascent (
    ascent_id SERIAL PRIMARY KEY,
    climb_id INT NOT NULL REFERENCES climb(climb_id),
    user_id INT NOT NULL REFERENCES users(users_id),
    grade TEXT NOT NULL,
    weight TEXT NOT NULL,
    comment TEXT NOT NULL,
    attempts TEXT NOT NULL,
    ascent_date TIMESTAMP NOT NULL,
    created_by INT NOT NULL REFERENCES users(users_id),
    created_at TIMESTAMP NOT NULL DEFAULT current_date,
    updated_at TIMESTAMP NOT NULL DEFAULT current_date
);

INSERT INTO COUNTRY(name) VALUES('United States');
INSERT INTO COUNTRY(NAME) VALUES('Afghanistan');
INSERT INTO COUNTRY(NAME) VALUES('Albania');
INSERT INTO COUNTRY(NAME) VALUES('Algeria');
INSERT INTO COUNTRY(NAME) VALUES('Andorra');
INSERT INTO COUNTRY(NAME) VALUES('Angola');
INSERT INTO COUNTRY(NAME) VALUES('Argentina');
INSERT INTO COUNTRY(NAME) VALUES('Armenia');
INSERT INTO COUNTRY(NAME) VALUES('Australia');
INSERT INTO COUNTRY(NAME) VALUES('Austria');
INSERT INTO COUNTRY(NAME) VALUES('Belarus');
INSERT INTO COUNTRY(NAME) VALUES('Belgium');
INSERT INTO COUNTRY(NAME) VALUES('Belize');
INSERT INTO COUNTRY(NAME) VALUES('Bolivia');
INSERT INTO COUNTRY(NAME) VALUES('Brazil');
INSERT INTO COUNTRY(NAME) VALUES('Bulgaria');
INSERT INTO COUNTRY(NAME) VALUES('Burundi');
INSERT INTO COUNTRY(NAME) VALUES('Cambodia');
INSERT INTO COUNTRY(NAME) VALUES('Canada');
INSERT INTO COUNTRY(NAME) VALUES('Chile');
INSERT INTO COUNTRY(NAME) VALUES('China');
INSERT INTO COUNTRY(NAME) VALUES('Colombia');
INSERT INTO COUNTRY(NAME) VALUES('Comoros');
INSERT INTO COUNTRY(NAME) VALUES('Congo');
INSERT INTO COUNTRY(NAME) VALUES('Costa Rica');
INSERT INTO COUNTRY(NAME) VALUES('Croatia');
INSERT INTO COUNTRY(NAME) VALUES('Cuba');
INSERT INTO COUNTRY(NAME) VALUES('Czech Republic');
INSERT INTO COUNTRY(NAME) VALUES('Denmark');
INSERT INTO COUNTRY(NAME) VALUES('Dominica');
INSERT INTO COUNTRY(NAME) VALUES('Dominican Republic');
INSERT INTO COUNTRY(NAME) VALUES('Ecuador');
INSERT INTO COUNTRY(NAME) VALUES('Egypt');
INSERT INTO COUNTRY(NAME) VALUES('El Salvador');
INSERT INTO COUNTRY(NAME) VALUES('Equatorial Guinea');
INSERT INTO COUNTRY(NAME) VALUES('Estonia');
INSERT INTO COUNTRY(NAME) VALUES('Ethiopia');
INSERT INTO COUNTRY(NAME) VALUES('Fiji');
INSERT INTO COUNTRY(NAME) VALUES('Finland');
INSERT INTO COUNTRY(NAME) VALUES('France');
INSERT INTO COUNTRY(NAME) VALUES('Gabon');
INSERT INTO COUNTRY(NAME) VALUES('Gambia');
INSERT INTO COUNTRY(NAME) VALUES('Georgia');
INSERT INTO COUNTRY(NAME) VALUES('Germany');
INSERT INTO COUNTRY(NAME) VALUES('Ghana');
INSERT INTO COUNTRY(NAME) VALUES('Greece');
INSERT INTO COUNTRY(NAME) VALUES('Grenada');
INSERT INTO COUNTRY(NAME) VALUES('Guatemala');
INSERT INTO COUNTRY(NAME) VALUES('Guinea');
INSERT INTO COUNTRY(NAME) VALUES('Guyana');
INSERT INTO COUNTRY(NAME) VALUES('Haiti');
INSERT INTO COUNTRY(NAME) VALUES('Honduras');
INSERT INTO COUNTRY(NAME) VALUES('Hungary');
INSERT INTO COUNTRY(NAME) VALUES('Iceland');
INSERT INTO COUNTRY(NAME) VALUES('India');
INSERT INTO COUNTRY(NAME) VALUES('Indonesia');
INSERT INTO COUNTRY(NAME) VALUES('Iran');
INSERT INTO COUNTRY(NAME) VALUES('Iraq');
INSERT INTO COUNTRY(NAME) VALUES('Ireland {Republic}');
INSERT INTO COUNTRY(NAME) VALUES('Israel');
INSERT INTO COUNTRY(NAME) VALUES('Italy');
INSERT INTO COUNTRY(NAME) VALUES('Ivory Coast');
INSERT INTO COUNTRY(NAME) VALUES('Jamaica');
INSERT INTO COUNTRY(NAME) VALUES('Japan');
INSERT INTO COUNTRY(NAME) VALUES('Jordan');
INSERT INTO COUNTRY(NAME) VALUES('Kazakhstan');
INSERT INTO COUNTRY(NAME) VALUES('Kenya');
INSERT INTO COUNTRY(NAME) VALUES('Korea North');
INSERT INTO COUNTRY(NAME) VALUES('Korea South');
INSERT INTO COUNTRY(NAME) VALUES('Kuwait');
INSERT INTO COUNTRY(NAME) VALUES('Kyrgyzstan');
INSERT INTO COUNTRY(NAME) VALUES('Laos');
INSERT INTO COUNTRY(NAME) VALUES('Lebanon');
INSERT INTO COUNTRY(NAME) VALUES('Liberia');
INSERT INTO COUNTRY(NAME) VALUES('Libya');
INSERT INTO COUNTRY(NAME) VALUES('Lithuania');
INSERT INTO COUNTRY(NAME) VALUES('Luxembourg');
INSERT INTO COUNTRY(NAME) VALUES('Macedonia');
INSERT INTO COUNTRY(NAME) VALUES('Madagascar');
INSERT INTO COUNTRY(NAME) VALUES('Malawi');
INSERT INTO COUNTRY(NAME) VALUES('Malaysia');
INSERT INTO COUNTRY(NAME) VALUES('Maldives');
INSERT INTO COUNTRY(NAME) VALUES('Mexico');
INSERT INTO COUNTRY(NAME) VALUES('Monaco');
INSERT INTO COUNTRY(NAME) VALUES('Mongolia');
INSERT INTO COUNTRY(NAME) VALUES('Morocco');
INSERT INTO COUNTRY(NAME) VALUES('Mozambique');
INSERT INTO COUNTRY(NAME) VALUES('Namibia');
INSERT INTO COUNTRY(NAME) VALUES('Nepal');
INSERT INTO COUNTRY(NAME) VALUES('Netherlands');
INSERT INTO COUNTRY(NAME) VALUES('New Zealand');
INSERT INTO COUNTRY(NAME) VALUES('Nicaragua');
INSERT INTO COUNTRY(NAME) VALUES('Niger');
INSERT INTO COUNTRY(NAME) VALUES('Nigeria');
INSERT INTO COUNTRY(NAME) VALUES('Norway');
INSERT INTO COUNTRY(NAME) VALUES('Oman');
INSERT INTO COUNTRY(NAME) VALUES('Pakistan');
INSERT INTO COUNTRY(NAME) VALUES('Panama');
INSERT INTO COUNTRY(NAME) VALUES('Papua New Guinea');
INSERT INTO COUNTRY(NAME) VALUES('Paraguay');
INSERT INTO COUNTRY(NAME) VALUES('Peru');
INSERT INTO COUNTRY(NAME) VALUES('Philippines');
INSERT INTO COUNTRY(NAME) VALUES('Poland');
INSERT INTO COUNTRY(NAME) VALUES('Portugal');
INSERT INTO COUNTRY(NAME) VALUES('Qatar');
INSERT INTO COUNTRY(NAME) VALUES('Romania');
INSERT INTO COUNTRY(NAME) VALUES('Rwanda');
INSERT INTO COUNTRY(NAME) VALUES('Saudi Arabia');
INSERT INTO COUNTRY(NAME) VALUES('Senegal');
INSERT INTO COUNTRY(NAME) VALUES('Serbia');
INSERT INTO COUNTRY(NAME) VALUES('Singapore');
INSERT INTO COUNTRY(NAME) VALUES('Slovakia');
INSERT INTO COUNTRY(NAME) VALUES('Slovenia');
INSERT INTO COUNTRY(NAME) VALUES('Somalia');
INSERT INTO COUNTRY(NAME) VALUES('South Africa');
INSERT INTO COUNTRY(NAME) VALUES('South Sudan');
INSERT INTO COUNTRY(NAME) VALUES('Spain');
INSERT INTO COUNTRY(NAME) VALUES('Sri Lanka');
INSERT INTO COUNTRY(NAME) VALUES('Sudan');
INSERT INTO COUNTRY(NAME) VALUES('Swaziland');
INSERT INTO COUNTRY(NAME) VALUES('Sweden');
INSERT INTO COUNTRY(NAME) VALUES('Switzerland');
INSERT INTO COUNTRY(NAME) VALUES('Syria');
INSERT INTO COUNTRY(NAME) VALUES('Taiwan');
INSERT INTO COUNTRY(NAME) VALUES('Tanzania');
INSERT INTO COUNTRY(NAME) VALUES('Thailand');
INSERT INTO COUNTRY(NAME) VALUES('Togo');
INSERT INTO COUNTRY(NAME) VALUES('Tonga');
INSERT INTO COUNTRY(NAME) VALUES('Trinidad & Tobago');
INSERT INTO COUNTRY(NAME) VALUES('Turkey');
INSERT INTO COUNTRY(NAME) VALUES('Uganda');
INSERT INTO COUNTRY(NAME) VALUES('Ukraine');
INSERT INTO COUNTRY(NAME) VALUES('United Arab Emirates');
INSERT INTO COUNTRY(NAME) VALUES('United Kingdom');
INSERT INTO COUNTRY(NAME) VALUES('Uruguay');
INSERT INTO COUNTRY(NAME) VALUES('Uzbekistan');
INSERT INTO COUNTRY(NAME) VALUES('Venezuela');
INSERT INTO COUNTRY(NAME) VALUES('Vietnam');
INSERT INTO COUNTRY(NAME) VALUES('Yemen');
INSERT INTO COUNTRY(NAME) VALUES('Zambia');
INSERT INTO COUNTRY(NAME) VALUES('Zimbabwe');

-- +goose Down
DROP TABLE climb_draft;
DROP TABLE ascent;
DROP TABLE climb;
DROP TABLE area;
DROP TABLE country;